#!/bin/bash
#-------------------------------------------------------------------------------
#
# install_mysql
#
#-------------------------------------------------------------------------------
# Properties

HELP="
The install_mysql command installs and configures the MySQL database server.

WARNING: This script has only been tested with 8.04 LTS.

--------------------------------------------------------------------------------

 Developed by Adrian Webb of http://collectivecolors.com
 Licensed under GPL v2

 See the project page at:  http://github.com/collectivecolors/web-admin
 Report issues here:       http://github.com/collectivecolors/web-admin/issues
 
--------------------------------------------------------------------------------
"

USAGE="
usage: install_mysql [ -h | --help ]                # Show usage information
                     -----------------------------------------------------------
                     [ -o | --override-dir <dir> ]  # Directory that contains server overrides
                                                    # Defaults to <cmd-dir>/overrides
"


# Get the directory of this command.

CMD_NAME=`basename $0`
INIT_DIR=`which $CMD_NAME`

if [ ! "$INIT_DIR" ]
then
  CMD_NAME=`readlink -f $0`

  cd `dirname $CMD_NAME`
  INIT_DIR=`pwd`

else
  INIT_DIR=`readlink -f $INIT_DIR`
  INIT_DIR=`dirname $INIT_DIR`
fi

OVERRIDE_DIR="$INIT_DIR/overrides"    


# Parse parameters

while test $# -ne 0
do
	case "$1" in
	  
  -h|--help)
    echo "$HELP"
    echo "$USAGE"
    exit 0;;
  
	-o|--override-dir)
    if [ ! "$2" ] || [ ! -d "$2" ]
    then
      echo "Override directory option requires an existing directory name."
      echo "$USAGE"
      exit 1
    fi
    
		OVERRIDE_DIR="$2"
    shift;;
	  
	*) break;;
	esac
	shift
done


#-------------------------------------------------------------------------------
# Start

echo "Installing the MySQL database server."
sudo aptitude install mysql-server || exit 2

echo "Configuring MySQL."
sudo cp -f "$OVERRIDE_DIR/my.cnf" /etc/mysql/my.cnf || exit 3

echo "Reinitializing the database server."
sudo /etc/init.d/mysql restart || exit 4 


echo "The MySQL database server has been successfully installed and configured."