#!/bin/bash
#-------------------------------------------------------------------------------
#
# install_git
#
#-------------------------------------------------------------------------------
# Properties



#-------------------------------------------------------------------------------
# Start

echo "Installing the Git version control system."

sudo aptitude install git-core \
                      git-doc \
                      git-daemon-run || exit 1