#!/bin/bash
#-------------------------------------------------------------------------------
#
# install_utilities
#
#-------------------------------------------------------------------------------
# Properties



#-------------------------------------------------------------------------------
# Start

echo "Installing general utilities."

sudo aptitude install zip \
                      unzip \
                      libmagic-dev \
                      imagemagick \
 || exit 1